version: "2.1"

services:
  mysql:
      extends:
          file: ./external_files/docker-db.yml
          service: mysql
      ports:
          - "3307:3306"
      volumes:
          - ../data/mysql:/data/mysql
  mongo:
      extends:
          file: ./external_files/docker-db.yml
          service: mongo
      ports:
          - "27018:27017"
      volumes:
          - ../data/mongo:/data/db
  redis:
      extends:
          file: ./external_files/docker-db.yml
          service: redis
      ports:
          - "6380:6379"
      volumes:
          - ../data/redis:/data
  elasticsearch:
      extends:
          file: ./elasticsearch/docker-compose.yml
          service: elasticsearch
      ports:
          - "9201:9200"
      volumes:
          - ../data/elasticsearch/data:/usr/share/elasticsearch/data
          - ../data/elasticsearch/config:/usr/share/elasticsearch/config
      environment:
          TZ: Asia/Chongqin
  php_nginx:
      container_name: php_nginx
      build:
        context: ./php_nginx
        dockerfile: Dockerfile
      ports:
        - "80:80"
      links:
        - "mysql"
        - "redis"
        #- "mongo"
      volumes:
        - ../data/php_nginx/log:/data/web/log
        - ../data/php_nginx/www:/data/web/www