version: "2.1"

services:
  mysql:
      extends:
          file: ./external_files/docker-db-registry.yml
          service: mysql
      ports:
          - "3307:3306"
      volumes:
          - ../data/mysql:/data/mysql
  mongo:
      extends:
          file: ./external_files/docker-db-registry.yml
          service: mongo
      ports:
          - "27018:27017"
      volumes:
          - ../data/mongo:/data/db
  redis:
      extends:
          file: ./external_files/docker-db-registry.yml
          service: redis
      ports:
          - "6380:6379"
      volumes:
          - ../data/redis:/data
  elasticsearch:
      extends:
          file: ./elasticsearch/docker-compose.yml
          service: elasticsearch
      ports:
          - "9201:9200"
      volumes:
          - ../data/elasticsearch/data:/usr/share/elasticsearch/data
          - ../data/elasticsearch/config:/usr/share/elasticsearch/config
      environment:
          TZ: Asia/Chongqing
  php_nginx:
      container_name: php_nginx
      image: hub.c.163.com/workhardsmile/lnmp-alpine:php-nginx-1.0
      restart: always
      ports:
        - "80:80"
      links:
        - "mysql"
        - "redis"
        - "elasticsearch"
        #- "mongo"
      volumes:
        - ../data/php_nginx/log:/data/web/log
        - ../data/php_nginx/www:/data/web/www