version: "2.1"

services:
  mysql:
      container_name: mysql
      build:
        context: ./mysql
        dockerfile: Dockerfile
      environment:
        MYSQL_ROOT_PASSWORD: 111111
      ports:
        - "3307:3306"
      volumes:
        - ../data/mysql:/data/mysql
  mongo:
      container_name: mongo
      build:
        context: ./mongo
        dockerfile: Dockerfile
      ports:
        - "27018:27017"
      volumes:
        - ../data/mongo:/data/db
  redis:
      container_name: redis
      build:
        context: ./redis
        dockerfile: Dockerfile
      ports:
        - "6380:6379"
      volumes:
        - ../data/redis:/data
  elasticsearch:
      extends:
          file: ./elasticsearch/docker-compose.yml
          service: elasticsearch
      ports:
          - "9201:9200"
      volumes:
          - ../data/elasticsearch/data:/usr/share/elasticsearch/data
          - ../data/elasticsearch/config:/usr/share/elasticsearch/config
      environment:
          TZ: Asia/Chongqing
  php_nginx:
      container_name: php_nginx
      build:
        context: ./php_nginx/project_conf
        dockerfile: Dockerfile
      ports:
        - "80:80"
        - "443:443"
      links:
        - "mysql"
        - "redis"
        - "elasticsearch"
        #- "mongo"
      volumes:
        - ../data/php_nginx/log:/data/web/log
        - ../data/php_nginx/www:/data/web/www
        - ../data/php_nginx/conf:/data/web/conf