version: "2.1"

services:
  mongo:
    container_name: mongo
    build:
      context: ../mongo
      dockerfile: Dockerfile
  mysql:
    container_name: mysql
    build:
      context: ../mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 111111
  redis:
      container_name: redis
      build:
        context: ../redis
        dockerfile: Dockerfile